CREATE SEQUENCE IF NOT EXISTS instructor_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS user_role_id_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE auth_tokens
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    user_id       BIGINT                                  NOT NULL,
    access_token  VARCHAR(255)                            NOT NULL,
    refresh_token VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_auth_tokens PRIMARY KEY (id)
);

CREATE TABLE coupons
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    code               VARCHAR(50)                             NOT NULL,
    name               VARCHAR(255),
    description        TEXT,
    discount_type      VARCHAR(10)                             NOT NULL,
    discount_value     DECIMAL(10, 2)                          NOT NULL,
    min_amount         DECIMAL(10, 2),
    max_discount       DECIMAL(10, 2),
    usage_limit        INTEGER,
    used_count         INTEGER,
    valid_from         TIMESTAMP WITHOUT TIME ZONE,
    valid_until        TIMESTAMP WITHOUT TIME ZONE,
    is_active          BOOLEAN,
    applicable_courses TEXT,
    created_by         BIGINT,
    CONSTRAINT pk_coupons PRIMARY KEY (id)
);

CREATE TABLE enrollments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    course_id          BIGINT,
    course_group_id    BIGINT,
    order_id           BIGINT,
    enrollment_date    TIMESTAMP WITHOUT TIME ZONE,
    completed_at       TIMESTAMP WITHOUT TIME ZONE,
    last_accessed      TIMESTAMP WITHOUT TIME ZONE,
    end_date           TIMESTAMP WITHOUT TIME ZONE,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_enrollments PRIMARY KEY (id)
);
CREATE TABLE instructors
(
    id               BIGINT NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id          BIGINT NOT NULL,
    expertise        TEXT,
    experience_years INTEGER,
    qualification    TEXT,
    bank_account     VARCHAR(50),
    bank_name        VARCHAR(100),
    tax_code         VARCHAR(20),
    slug             VARCHAR(255),
    commission_rate  DECIMAL(5, 2),
    total_revenue    DECIMAL(15, 2),
    CONSTRAINT pk_instructors PRIMARY KEY (id)
);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSE_ON_INSTRUCTOR
        FOREIGN KEY (instructor_id) REFERENCES instructors (id);

CREATE TABLE order_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    order_id        BIGINT                                  NOT NULL,
    course_id       BIGINT,
    course_group_id BIGINT,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    user_id         BIGINT                                  NOT NULL,
    order_number    VARCHAR(50)                             NOT NULL,
    total_amount    DECIMAL(10, 2)                          NOT NULL,
    currency        VARCHAR(3),
    notes           TEXT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE questions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    quiz_id        BIGINT                                  NOT NULL,
    question_text  TEXT                                    NOT NULL,
    question_type  VARCHAR(20)                             NOT NULL,
    options        TEXT,
    correct_answer TEXT,
    explanation    TEXT,
    points         DECIMAL(5, 2),
    sort_order     INTEGER,
    CONSTRAINT pk_questions PRIMARY KEY (id)
);

CREATE TABLE quiz_attempts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    quiz_id      BIGINT                                  NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    score        DECIMAL(5, 2),
    total_points DECIMAL(5, 2),
    answers      TEXT,
    time_taken   INTEGER,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_quiz_attempts PRIMARY KEY (id)
);

CREATE TABLE quizzes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    course_id     BIGINT                                  NOT NULL,
    lesson_id     BIGINT,
    title         VARCHAR(255)                            NOT NULL,
    description   TEXT,
    time_limit    INTEGER,
    max_attempts  INTEGER,
    passing_score DECIMAL(5, 2),
    is_active     BOOLEAN,
    CONSTRAINT pk_quizzes PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    user_id       BIGINT                                  NOT NULL,
    course_id     BIGINT                                  NOT NULL,
    enrollment_id BIGINT                                  NOT NULL,
    rating        INTEGER,
    comment       TEXT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        role_name DEFAULT 'STUDENT',
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE study_schedules
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    user_id        BIGINT                                  NOT NULL,
    course_id      BIGINT                                  NOT NULL,
    scheduled_date date                                    NOT NULL,
    scheduled_time time WITHOUT TIME ZONE,
    title          VARCHAR(255),
    description    TEXT,
    is_completed   BOOLEAN,
    reminder_sent  BOOLEAN,
    CONSTRAINT pk_study_schedules PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    id BIGINT NOT NULL ,
    user_id     BIGINT  NOT NULL,
    role_id     INTEGER NOT NULL,
    assigned_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);

ALTER TABLE enrollments
    ADD CONSTRAINT uc_6c8d6aa5e27c938c0b7ce5c28 UNIQUE (user_id, course_id);

ALTER TABLE reviews
    ADD CONSTRAINT uc_b9cf3964b3240ca600d5f2b68 UNIQUE (user_id, course_id);

ALTER TABLE coupons
    ADD CONSTRAINT uc_coupons_code UNIQUE (code);

ALTER TABLE instructors
    ADD CONSTRAINT uc_instructors_user UNIQUE (user_id);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_order_number UNIQUE (order_number);



ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE auth_tokens
    ADD CONSTRAINT FK_AUTH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE coupons
    ADD CONSTRAINT FK_COUPONS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_COURSE_GROUP FOREIGN KEY (course_group_id) REFERENCES course_groups (id);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);



ALTER TABLE instructors
    ADD CONSTRAINT FK_INSTRUCTORS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_COURSE_GROUP FOREIGN KEY (course_group_id) REFERENCES course_groups (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE questions
    ADD CONSTRAINT FK_QUESTIONS_ON_QUIZ FOREIGN KEY (quiz_id) REFERENCES quizzes (id);

ALTER TABLE quizzes
    ADD CONSTRAINT FK_QUIZZES_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE quizzes
    ADD CONSTRAINT FK_QUIZZES_ON_LESSON FOREIGN KEY (lesson_id) REFERENCES lessons (id);

ALTER TABLE quiz_attempts
    ADD CONSTRAINT FK_QUIZ_ATTEMPTS_ON_QUIZ FOREIGN KEY (quiz_id) REFERENCES quizzes (id);

ALTER TABLE quiz_attempts
    ADD CONSTRAINT FK_QUIZ_ATTEMPTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_ENROLLMENT FOREIGN KEY (enrollment_id) REFERENCES enrollments (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE study_schedules
    ADD CONSTRAINT FK_STUDY_SCHEDULES_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE study_schedules
    ADD CONSTRAINT FK_STUDY_SCHEDULES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);