-- CREATE LESSON PROGRESS --

CREATE SEQUENCE IF NOT EXISTS lesson_progress_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS lesson_progress (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   lesson_id BIGINT,
   user_id BIGINT,
   enrollment_id BIGINT,
   is_done BOOLEAN DEFAULT false,
   CONSTRAINT pk_lesson_progress PRIMARY KEY (id)
);

ALTER TABLE lesson_progress
    ADD CONSTRAINT fk_lesson_progress_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id);

ALTER TABLE lesson_progress
    ADD CONSTRAINT fk_lesson_progress_user FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE lesson_progress
    ADD CONSTRAINT fk_lesson_progress_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(id);

-- UPDATE COURSE GROUP --
ALTER TABLE course_groups
    ADD COLUMN IF NOT EXISTS currency currency;